spring:
  application:
    name: bifai-backend
  profiles:
    active: dev
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
  
  # Datasource Configuration (will be overridden by profiles)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 커넥션 풀 기본 설정
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000        # 10분
      connection-timeout: 30000   # 30초
      max-lifetime: 1800000       # 30분
      
      # 성능 최적화 설정
      pool-name: BifHikariCP
      register-mbeans: true
      leak-detection-threshold: 60000  # 1분
      validation-timeout: 5000         # 5초
      initialization-fail-timeout: 60000  # 1분
      
      # 데이터베이스별 최적화 설정은 DatabaseConfig에서 처리
  
  # Redis Configuration
  data:
    redis:
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  # Security Configuration
  security:
    user:
      name: ${SECURITY_USER_NAME:admin}
      password: ${SECURITY_USER_PASSWORD:changeme}
  
  # Flyway Configuration
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 1
    validate-on-migrate: true
    clean-disabled: true
    out-of-order: false
    placeholder-replacement: true

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

# Logging Configuration
logging:
  level:
    root: INFO
    com.bifai.reminder: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/bifai-backend.log
    max-size: 10MB
    max-history: 30

# Application Configuration
app:
  name: BIF-AI Reminder Backend
  version: 0.0.1
  description: 경계선 지능 대상자를 위한 상황 인지 보조 시스템
  
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:YmlmYWlSZW1pbmRlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjIwMjQ=}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}    # 15분 (15 * 60 * 1000)
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000} # 7일 (7 * 24 * 60 * 60 * 1000)

# BIF 서비스 전용 데이터베이스 설정
bif:
  database:
    # 커넥션 풀 상세 설정
    connection-pool:
      maximum-pool-size: ${BIF_DB_MAX_POOL_SIZE:10}
      minimum-idle: ${BIF_DB_MIN_IDLE:5}
      idle-timeout: ${BIF_DB_IDLE_TIMEOUT:600000}
      connection-timeout: ${BIF_DB_CONNECTION_TIMEOUT:30000}
      max-lifetime: ${BIF_DB_MAX_LIFETIME:1800000}
      leak-detection-threshold: ${BIF_DB_LEAK_THRESHOLD:60000}
      validation-timeout: ${BIF_DB_VALIDATION_TIMEOUT:5000}
      initialization-fail-timeout: ${BIF_DB_INIT_FAIL_TIMEOUT:60000}
    
    # 쿼리 최적화 설정
    query-optimization:
      batch-size: 25
      fetch-size: 100
      query-timeout: 30
      slow-query-threshold: 1000
      query-plan-cache-size: 2048
      prepared-statement-cache-size: 250
    
    # 모니터링 설정
    monitoring:
      enable-statistics: ${BIF_DB_ENABLE_STATS:false}
      log-slow-queries: true
      log-connection-state: true
      metrics-collection-interval: 60
      enable-jmx: true
    
    # 보안 설정
    security:
      use-ssl: ${BIF_DB_USE_SSL:false}
      verify-ssl-certificate: true
      encrypt-connection: false
      enable-sql-injection-prevention: true
      mask-sensitive-data: true