spring:
  # Production Database Configuration
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  
  # JPA Production Settings
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  
  # Redis Production Configuration
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl: true

# Production Server Configuration
server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Production Logging
logging:
  level:
    root: ERROR
    com.bifai.reminder: WARN
    org.springframework.web: WARN
  file:
    name: /var/log/bifai/bifai-backend.log
    max-size: 50MB
    max-history: 90

# Flyway Production Configuration
flyway:
  enabled: true
  baseline-on-migrate: false
  locations: classpath:db/migration
  validate-on-migrate: true
  out-of-order: false

# Production Security
app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      expiration: 900000 # 15 minutes
      refresh-expiration: 86400000 # 1 day
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:https://www.bifai.com,https://bifai.com}
    allowed-methods: GET,POST,PUT,DELETE
    allowed-headers: Authorization,Content-Type,Accept
    allow-credentials: true