spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
    show-sql: true
    open-in-view: false
  
  h2:
    console:
      enabled: true
      path: /h2-console

# 로깅 설정
logging:
  level:
    org.hibernate: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    com.bifai.reminder.bifai_backend: DEBUG

# Flyway 비활성화
  flyway:
    enabled: false

# Security 간소화
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: test
            client-secret: test