spring:
  # H2 데이터베이스 설정 (로컬 테스트용)
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  # H2 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console
    
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
    
  # Flyway 비활성화 (H2 사용시)
  flyway:
    enabled: false
    
  # Redis 비활성화
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - org.springframework.boot.autoconfigure.data.redis.RedisRepositoriesAutoConfiguration
      
  # OAuth2 설정 (로컬 테스트용)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: local-google-client-id
            client-secret: local-google-client-secret
            scope:
              - email
              - profile
          kakao:
            client-id: local-kakao-client-id
            client-secret: local-kakao-client-secret
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            scope:
              - profile_nickname
              - account_email
          naver:
            client-id: local-naver-client-id
            client-secret: local-naver-client-secret
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# JWT 설정
jwt:
  secret: local-jwt-secret-key-for-bifai-backend-application
  expiration: 3600000
  refresh-expiration: 604800000

# 로깅 설정
logging:
  level:
    root: INFO
    com.bifai.reminder: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG

# 서버 설정
server:
  port: 8080
  
# 액추에이터 설정
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always